# This is a TOML document. Boom
[consume]
    kafkaEnable = false
    redisEnable = true

[discovery]
    nodes = "http://10.0.41.145:2379,http://10.0.41.145:2479,http://10.0.41.145:2579"

[kafka]
    topic = "goim-push-topic"
    group = "goim-push-group-job"
    brokers = ["10.0.41.145:9093","10.0.41.145:9094","10.0.41.145:9095"]

[redis]
    network = "tcp"
    addr = "10.0.41.145:6379"
    active = 60000
    idle = 1024
    dialTimeout = "200ms"
    readTimeout = "500ms"
    writeTimeout = "500ms"
    idleTimeout = "120s"
    expire = "30m"